// Generated by CoffeeScript 1.7.1
var CleanCSS, CleanCSSMinifier, sysPath;

CleanCSS = require('clean-css');

sysPath = require('path');

module.exports = CleanCSSMinifier = (function() {
  CleanCSSMinifier.prototype.brunchPlugin = true;

  CleanCSSMinifier.prototype.type = 'stylesheet';

  function CleanCSSMinifier(config) {
    var _ref, _ref1, _ref2;
    this.config = config;
    this.options = (_ref = (_ref1 = this.config) != null ? (_ref2 = _ref1.plugins) != null ? _ref2.cleancss : void 0 : void 0) != null ? _ref : {};
  }

  CleanCSSMinifier.prototype.optimize = function(data, path, callback) {
    var err, error, optimized;
    try {
      optimized = new CleanCSS(this.options).minify(data);
    } catch (_error) {
      err = _error;
      error = "CSS minify failed on " + path + ": " + err;
    }
    return process.nextTick(function() {
      return callback(error, optimized || data);
    });
  };

  return CleanCSSMinifier;

})();
